### PR TITLE
Allow user to set a 'from' address

### LINKED ISSUE #53: From address should be what the user submits
I noticed that the form email address is a global setting which won't work for anything going through RT. For form submissions going to RT, the from email address should be what the user sets. However I could see other use cases in the future where we may want to use a global or a per-form from address.

**This is a blocker for getting the site deployed on prod.**

### PR DESCRIPTION
**Pull request by athai**
Resolves #53

### CODE REVIEW

**Comment by mathuin** [comment]
http://tools.ietf.org/html/rfc6761

I'd use the example.org domain with an arbitrary username before using a real email address.

**Comment by matthewrsj** [comment]
Referencing this PR in my commit was a mistake.

@athai I agree with @mathuin, use an example email. I use `example@osuosl.org` so that it passes the email verifier that formsender uses.

**Comment by matthewrsj** [comment]
Once again, sorry. My errant commit message closed this.

**Comment by Kennric** [comment]
Looks good. +1

**Pull request merged**
