### PR TITLE
Add more logging info

### PR DESCRIPTION
**Pull request by athai**
WIP #51. 

Note: https://github.com/osuosl/formsender/pull/60/files#diff-0c3b79f514f76d507ede2c77ae608833R135 may need to be changed after form field(s) naming conventions are discussed.

### CODE REVIEW

**Comment by matthewrsj** [comment]
@athai this looks correct. Can you add the log output of a test run as a comment so we can be sure it is logging correctly?

**Comment by athai** [comment]
@matthewrsj What do you mean?

**Comment by matthewrsj** [comment]
@athai this is what I'm talking about: https://github.com/osuosl/formsender/pull/42

I can help with this later.

**Comment by athai** [comment]
Formsender now logs the full request at level DEBUG. After running tests, logs can be found in /var/log/syslog. The following is an example of the output.

Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: name is: Valid Guy
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender: sending email from: example@osuosl.org
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}
Mar 30 11:45:05 silver DEBUG formsender message: {'redirect': u'http://www.example.com', 'token': u'15674hsda//*q23%^13jnxccv3ds54sa4g4sa532323!OoRdsfISDIdks38*(dsfjk)aS', 'last_name': u'', 'name': u'Valid Guy', 'email': u'example@osuosl.org'}

**Comment by matthewrsj** [comment]
It should be mentioned that this is *some* of the output of the tests. The rest of the output includes the project name and other things that are requested by the issue. +1 from me.

**Comment by Kennric** [comment]
Looks good to me. +1

**Comment by matthewrsj** [comment]
@athai is this good to merge?

**Comment by athai** [comment]
@matthewrsj Yes. Although, I was waiting to see if we wanted to handle parsing for the project name differently, but that can be resolved later.

**Comment by Kennric** [comment]
+1 again

**Comment by ramereth** [comment]
@athai  I think this will work but I'd like to test it some more. Mind going ahead and merging this and if I run into anything new I'll make a new issue?

**Pull request merged**
