### PR TITLE
Python Webapp Configuration

### PR DESCRIPTION
**Pull request by matthewrsj**
Configured to build with python_webapp cookbook: https://github.com/osuosl-cookbooks/python-webapp 

Works on openstack vm.

### CODE REVIEW

**Comment by Kennric** [comment]
Looks like a pretty standard wsgi setup, I see no issues. +1

**Comment by tschuy** [comment]
I'm working on a PR for ``python-webapp`` that will allow you to put it in the root of the repo. This would require waiting for it to be reviewed by the Chef team, though. @Kennric thoughts?

**Comment by matthewrsj** [comment]
@tschuy does it matter that it's in its own folder, is it a style or convention thing?

**Comment by tschuy** [comment]
mostly I don't like that you had to create a folder just for this.

**Comment by tschuy** [comment]
+1, looks good

**Pull request merged**
