### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by matthewrsj**

### CODE REVIEW

**Comment by matthewrsj** [comment]
I'm opening this for feedback so I can start working on docker.

**Comment by ElijahCaine** [comment]
@matthewrsj This is a great improvement.

One idea I have for improving this doc is to include a little example page (test.html or something like that) which allows the user to test that they have it setup and working. Once that test page is created, writing a little 'Usage' section in the README about using the test document (set your email and token in conf.py, open test.html, send the form, check your email).

If that seems overly complicated I'd say this is good for now.

@Kennric thoughts?

**Comment by matthewrsj** [comment]
@ElijahCaine I actually had that, but having a form locally (on localhost:5000) requires additional rendering code in the application. I didn't want extra code so I removed it during my refactoring. The test form is still there under /templates/index.html it is just never rendered.

**Comment by matthewrsj** [comment]
@ElijahCaine, added your suggestion

**Comment by Kennric** [comment]
Looks good to me, nice and clear. +1

**Comment by ElijahCaine** [comment]
Looks good to me. The feedback was integrated well. +1

**Pull request merged**
