### PR TITLE
test wsgi level Sentry trap

### PR DESCRIPTION
**Pull request by Kennric**
Add top-level hook for Sentry exception monitoring

### CODE REVIEW

**Comment by Kennric** [comment]
@ramereth, @jldugger 
This pr add a wsgi-level hook for Sentry, which should catch anything not handled by exception handlers in the code.

**Comment by jldugger** [comment]
@Kennric where do we define RAVEN_URI?

**Comment by Kennric** [comment]
@jldugger it comes from the conf file, which is populated on deploy by ansible, see MR 19 on ansible_playbooks

**Comment by jldugger** [comment]
Sounds good!

**Pull request merged**
